### ISSUE TITLE
identity_type is called type_identity in the standard

### ISSUE THREAD

**Issue by jmairboeck** [MFHava/PTL#2]
According to [cppreference](https://en.cppreference.com/w/cpp/types/type_identity) the type trait is called `type_identity` in the standard. Should the version in [cpp20_emulation.hpp](https://github.com/MFHava/PTL/blob/992a2ebf450ae65e93e88ddd4d288fa5a897e847/inc/ptl/internal/cpp20_emulation.hpp#L13) be renamed to match the standard?

**Comment by MFHava** [comment]
Interesting, I have either messed up the name when adding this emulation, or the name was changed in between (guessing the former).
It probably should be changes, though it's only a minute issue in a temporary internal feature emulation...

**Comment by MFHava** [comment]
fixed
